import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, readFileSync } from 'node:fs';

try {
	for (const line of readFileSync('.env', 'utf8').split('\n')) {
		const m = line.match(/^(\w+)="?(.+?)"?\s*$/);
		if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
	}
} catch {}

const vaultPluginDir = process.env.OBSIDIAN_VAULT_PLUGIN_DIR;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: vaultPluginDir ? [{
		name: 'copy-to-vault',
		setup(build) {
			build.onEnd(() => {
				for (const f of ['main.js', 'manifest.json', 'styles.css']) {
					try { copyFileSync(f, `${vaultPluginDir}/${f}`); } catch {}
				}
			});
		},
	}] : [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
